/// Generated by build.rs; do not edit!

const fn box_drawing_5_by_5_bitmap(x11: u32, x12: u32, x13: u32, x14: u32, x15: u32,
                                   x21: u32, x22: u32, x23: u32, x24: u32, x25: u32,
                                   x31: u32, x32: u32, x33: u32, x34: u32, x35: u32,
                                   x41: u32, x42: u32, x43: u32, x44: u32, x45: u32,
                                   x51: u32, x52: u32, x53: u32, x54: u32, x55: u32) -> u32 {
	((x11) << 24) | ((x12) << 23) | ((x13) << 22) | ((x14) << 21) | ((x15) << 20) |
	 ((x21) << 19) | ((x22) << 18) | ((x23) << 17) | ((x24) << 16) | ((x25) << 15) |
	 ((x31) << 14) | ((x32) << 13) | ((x33) << 12) | ((x34) << 11) | ((x35) << 10) |
	 ((x41) <<  9) | ((x42) <<  8) | ((x43) <<  7) | ((x44) <<  6) | ((x45) <<  5) |
	 ((x51) <<  4) | ((x52) <<  3) | ((x53) <<  2) | ((x54) <<  1) | ((x55))
}

/// Definition of most of the glyphs in the 2500..257F range as 5x5 bitmaps
/// (bits 24..0 in the obvious order), see ../doc/boxes.txt

pub const DRAW_BOX_DRAWING_BITMAPS: [u32; 128] = [
	// U+2500 - light horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2501 - heavy horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+2502 - light vertical
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2503 - heavy vertical
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2504 - not handled here: light triple dash horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2505 - not handled here: heavy triple dash horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2506 - not handled here: light triple dash vertical
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2507 - not handled here: heavy triple dash vertical
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2508 - not handled here: light quadruple dash horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2509 - not handled here: heavy quadruple dash horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+250A - not handled here: light quadruple dash vertical
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+250B - not handled here: heavy quadruple dash vertical
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+250C - light down and right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+250D - down light and right heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+250E - down heavy and right light
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+250F - heavy down and right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
	),
	// U+2510 - light down and left
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2511 - down light and left heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2512 - down heavy and left light
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2513 - heavy down and left
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2514 - light up and right
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2515 - up light and right heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+2516 - up heavy and right light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2517 - heavy up and right
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+2518 - light up and left
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2519 - up light and left heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+251A - up heavy and left light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+251B - heavy up and left
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+251C - light vertical and right
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+251D - vertical light and right heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+251E - up heavy and right down light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+251F - down heavy and right up light
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2520 - vertical heavy and right light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2521 - down light and right up heavy
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+2522 - up light and right down heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
	),
	// U+2523 - heavy vertical and right
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
	),
	// U+2524 - light vertical and left
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2525 - vertical light and left heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2526 - up heavy and left down light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2527 - down heavy and left up light
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2528 - vertical heavy and left light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2529 - down light and left up heavy
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+252A - up light and left down heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+252B - heavy vertical and left
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+252C - light down and horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+252D - left heavy and right down light
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+252E - right heavy and left down light
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+252F - down light and horizontal heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+2530 - down heavy and horizontal light
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2531 - right light and left down heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2532 - left light and right down heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
	),
	// U+2533 - heavy down and horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
	),
	// U+2534 - light up and horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2535 - left heavy and right up light
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2536 - right heavy and left up light
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+2537 - up light and horizontal heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+2538 - up heavy and horizontal light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2539 - right light and left up heavy
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+253A - left light and right up heavy
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+253B - heavy up and horizontal
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+253C - light vertical and horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+253D - left heavy and right vertical light
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+253E - right heavy and left vertical light
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+253F - vertical light and horizontal heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+2540 - up heavy and down horizontal light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2541 - down heavy and up horizontal light
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2542 - vertical heavy and horizontal light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2543 - left up heavy and right down light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2544 - right up heavy and left down light
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+2545 - left down heavy and right up light
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+2546 - right down heavy and left up light
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
	),
	// U+2547 - down light and up horizontal heavy
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+2548 - up light and down horizontal heavy
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
	),
	// U+2549 - right light and left vertical heavy
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+254A - left light and right vertical heavy
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
	),
	// U+254B - heavy vertical and horizontal
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 1, 1, 1, 0, 
	),
	// U+254C - not handled here: light double dash horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+254D - not handled here: heavy double dash horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+254E - not handled here: light double dash vertical
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+254F - not handled here: heavy double dash vertical
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2550 - double horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+2551 - double vertical
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
	),
	// U+2552 - down single and right double
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+2553 - down double and right single
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
	),
	// U+2554 - double down and right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 1, 1, 1, 1, 
		0, 1, 0, 0, 0, 
		0, 1, 0, 1, 1, 
		0, 1, 0, 1, 0, 
	),
	// U+2555 - down single and left double
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2556 - down double and left single
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 0, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
	),
	// U+2557 - double down and left
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 0, 
		0, 0, 0, 1, 0, 
		1, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
	),
	// U+2558 - up single and right double
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+2559 - up double and right single
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		0, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+255A - double up and right
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 1, 
		0, 1, 0, 0, 0, 
		0, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+255B - up single and left double
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+255C - up double and left single
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+255D - double up and left
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		1, 1, 0, 1, 0, 
		0, 0, 0, 1, 0, 
		1, 1, 1, 1, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+255E - vertical single and right double
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+255F - vertical double and right single
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 1, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
	),
	// U+2560 - double vertical and right
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 1, 
		0, 1, 0, 0, 0, 
		0, 1, 0, 1, 1, 
		0, 1, 0, 1, 0, 
	),
	// U+2561 - vertical single and left double
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2562 - vertical double and left single
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		1, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
	),
	// U+2563 - double vertical and left
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		1, 1, 0, 1, 0, 
		0, 0, 0, 1, 0, 
		1, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
	),
	// U+2564 - down single and horizontal double
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+2565 - down double and horizontal single
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
	),
	// U+2566 - double down and horizontal
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		1, 1, 0, 1, 1, 
		0, 1, 0, 1, 0, 
	),
	// U+2567 - up single and horizontal double
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+2568 - up double and horizontal single
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2569 - double up and horizontal
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		1, 1, 0, 1, 1, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+256A - vertical single and horizontal double
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 0, 0, 
	),
	// U+256B - vertical double and horizontal single
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
		1, 1, 1, 1, 1, 
		0, 1, 0, 1, 0, 
		0, 1, 0, 1, 0, 
	),
	// U+256C - double vertical and horizontal
	box_drawing_5_by_5_bitmap(
		0, 1, 0, 1, 0, 
		1, 1, 0, 1, 1, 
		0, 0, 0, 0, 0, 
		1, 1, 0, 1, 1, 
		0, 1, 0, 1, 0, 
	),
	// U+256D - not handled here: light arc down and right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+256E - not handled here: light arc down and left
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+256F - not handled here: light arc up and left
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2570 - not handled here: light arc up and right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2571 - not handled here: light diagonal upper right to lower left
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2572 - not handled here: light diagonal upper left to lower right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2573 - not handled here: light diagonal cross
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2574 - light left
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2575 - light up
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2576 - light right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2577 - light down
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
	// U+2578 - heavy left
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+2579 - heavy up
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+257A - heavy right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+257B - heavy down
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+257C - light left and heavy right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		0, 0, 1, 1, 1, 
		1, 1, 1, 1, 1, 
		0, 0, 1, 1, 1, 
		0, 0, 0, 0, 0, 
	),
	// U+257D - light up and heavy down
	box_drawing_5_by_5_bitmap(
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
	),
	// U+257E - heavy left and light right
	box_drawing_5_by_5_bitmap(
		0, 0, 0, 0, 0, 
		1, 1, 1, 0, 0, 
		1, 1, 1, 1, 1, 
		1, 1, 1, 0, 0, 
		0, 0, 0, 0, 0, 
	),
	// U+257F - heavy up and light down
	box_drawing_5_by_5_bitmap(
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 1, 1, 1, 0, 
		0, 0, 1, 0, 0, 
		0, 0, 1, 0, 0, 
	),
];